VERSION="15.30"
LEDGER=[
{"branch":"OPTION_OI","status":"ARCHIVED","promoted":False,"reason":"Insufficient usable historical PCR/imbalance data for independent validation.","evidence":{"stored_days":214,"usable_days":11,"usable_nifty_bars":275}},
{"branch":"FUTURES_OI_BASIS","status":"ARCHIVED","promoted":False,"reason":"Expanded frozen validation failed stability and net-after-cost gates.","evidence":{"independent_signals":401,"weighted_accuracy_percent":56.1,"net_avg_bps":-1.49,"p_value":0.0144,"positive_folds":"1/4","worst_fold_accuracy_percent":50.0}},
{"branch":"TREND_LOW_VOL","status":"ARCHIVED","promoted":False,"reason":"Corrected merged-history frozen validation failed 3 of 6 predefined gates.","evidence":{"merged_unique_rows":13434,"feature_rows":13408,"independent_signals":212,"weighted_accuracy_percent":54.2,"gross_avg_bps":5.44,"net_avg_bps":2.44,"p_value":0.2164,"positive_folds":"2/4","worst_fold_accuracy_percent":50.0,"gates_passed":"3/6"}}
]
def setup_v1530(app):
    @app.get("/api/research/v1530-checkpoint")
    def checkpoint():
        promoted=[x for x in LEDGER if x["promoted"]]
        return {"status":"success","version":VERSION,"stage":"FINAL_RESEARCH_VALIDATION_CHECKPOINT","research_branches":LEDGER,"research_branches_promoted":len(promoted),"research_branch_promotion_list":[x["branch"] for x in promoted],"decision":"NO RESEARCH BRANCH PROMOTED","interpretation":"Completed independent/frozen research branches are archived under their predefined gates. No failed hypothesis is tuned or silently added to production.","v16_policy":{"baseline":"Preserve the existing live CE/PE/WAIT engine as the production baseline.","failed_research_features":"Do not add Option OI, Futures OI/Basis, or frozen TREND_LOW_VOL as validated edge components.","risk_layer":"Transaction-cost awareness, data-quality checks, timestamps, confidence transparency and WAIT behavior may be retained as engineering/risk controls; they are not claimed as validated predictive edge.","promotion_rule":"Any future predictive component must pass a separately defined out-of-sample/frozen validation before live promotion."},"next_version":"16.0","next_version_goal":"Consolidate the existing live prediction experience and engineering safeguards into one clean engine without promoting rejected research hypotheses.","live_routing_changed":False}
    @app.get("/api/research/v1530-roadmap")
    def roadmap():
        return {"status":"success","version":VERSION,"roadmap":[{"version":"15.30","state":"CURRENT","goal":"Close research checkpoint and freeze promotion decisions."},{"version":"16.0","state":"NEXT","goal":"Unified production engine; preserve baseline and add engineering safeguards only."},{"version":"16.1","state":"PLANNED","goal":"Forward/paper validation of CE/PE/WAIT, entry, target and stop-loss outputs."},{"version":"17.0","state":"PLANNED","goal":"Stable production dashboard, prediction chart, timestamps and alerts."}],"additional_v15_research_versions_planned":0,"live_routing_changed":False}
